### 🔹 What is a DataFrame?

##### A DataFrame in Pandas is a two-dimensional table-like data structure used to store and organize data.

##### 👉 Think of it like:

##### An Excel sheet 📊
##### Or a database table

### 1. Import Libraries

In [1]:
import numpy as np 
import pandas as pd

#### 2. Creating DataFrame from Dictionary

In [2]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### 3. Creating DataFrame from List

In [3]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

In [4]:
df2 = pd.DataFrame(data_list)

In [5]:
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [6]:
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [7]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### 4. Selecting Columns

In [8]:
df2["City"]

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [9]:
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

#### 5. Creating a New Column

In [24]:
df2["Roll"] = ["Doctor","Eng.","Doctor","Eng."]

In [25]:
df2["Designation"] = ["Doctor","Eng.","Doctor","Eng."]

In [26]:
df2

    Name  Age      City  Salary    Roll Designation
0   John   28  New York   65000  Doctor      Doctor
1   Anna   34     Paris   70000    Eng.        Eng.
2  Peter   29    Berlin   62000  Doctor      Doctor
3  Linda   42    London   85000    Eng.        Eng.

#### 6. Removing Rows / Columns

In [27]:
df2.drop(0, axis=0)

    Name  Age    City  Salary    Roll Designation
1   Anna   34   Paris   70000    Eng.        Eng.
2  Peter   29  Berlin   62000  Doctor      Doctor
3  Linda   42  London   85000    Eng.        Eng.

In [30]:
df2.drop("Roll", axis=1)

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [28]:
df2.drop("Designation", axis=1)

    Name  Age      City  Salary    Roll
0   John   28  New York   65000  Doctor
1   Anna   34     Paris   70000    Eng.
2  Peter   29    Berlin   62000  Doctor
3  Linda   42    London   85000    Eng.

In [32]:
df2.drop(["Designation","Roll"], axis=1, inplace=True)

In [33]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### 7. Selecting Rows

In [36]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [17]:
df.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

#### 8. Selecting Rows + Columns

In [18]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

#### 9. Conditional Selection (Filtering)

In [19]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [20]:
#I only want to see those people whose age is above 30

In [21]:
df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [22]:
#I only want poeple whose age is above 30 and their city must be paris

In [23]:
df2[(df2["Age"] > 30) & (df2["City"] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000