#### 1. What is a Pivot Table?

##### 👉 A pivot table is used to:

##### Summarize and analyze data by grouping rows and columns

##### ✔️ Similar to Excel Pivot Table

In [2]:
import numpy as np 
import pandas as pd

#### Pivot Table

In [4]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

In [5]:
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    778     41   John
1  2023-01-02       B   West    216     68   Mary
2  2023-01-03       C  North    353     78    Bob
3  2023-01-04       D  South    850     49  Alice
4  2023-01-05       A   East    609     51   John
5  2023-01-06       B   West    619     49   Mary
6  2023-01-07       C  North    813     19    Bob
7  2023-01-08       D  South    849     23  Alice
8  2023-01-09       A   East    201     54   John
9  2023-01-10       B   West    610     93   Mary
10 2023-01-11       C  North    439     29    Bob
11 2023-01-12       D  South    753     56  Alice
12 2023-01-13       A   East    631     57   John
13 2023-01-14       B   West    329     77   Mary
14 2023-01-15       C  North    193     77    Bob
15 2023-01-16       D  South    109     19  Alice
16 2023-01-17       A   East    983     26   John
17 2023-01-18       B   West    943     73   Mary
18 2023-01-19       C  North    193     65    Bob
19 2023-01-20       D  South    768     99  Alice

#### 2. Creating New Columns

In [6]:
df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    778     41   John  January      Q1
1  2023-01-02       B   West    216     68   Mary  January      Q1
2  2023-01-03       C  North    353     78    Bob  January      Q1
3  2023-01-04       D  South    850     49  Alice  January      Q1
4  2023-01-05       A   East    609     51   John  January      Q1
5  2023-01-06       B   West    619     49   Mary  January      Q1
6  2023-01-07       C  North    813     19    Bob  January      Q1
7  2023-01-08       D  South    849     23  Alice  January      Q1
8  2023-01-09       A   East    201     54   John  January      Q1
9  2023-01-10       B   West    610     93   Mary  January      Q1
10 2023-01-11       C  North    439     29    Bob  January      Q1
11 2023-01-12       D  South    753     56  Alice  January      Q1
12 2023-01-13       A   East    631     57   John  January      Q1
13 2023-01-14       B   West    329     77   Mary  January      Q1
14 2023-01-15       C  North    193     77    Bob  January      Q1
15 2023-01-16       D  South    109     19  Alice  January      Q1
16 2023-01-17       A   East    983     26   John  January      Q1
17 2023-01-18       B   West    943     73   Mary  January      Q1
18 2023-01-19       C  North    193     65    Bob  January      Q1
19 2023-01-20       D  South    768     99  Alice  January      Q1

#### 3. Basic Pivot Table

In [7]:
pd.pivot_table(df, values="Sales", index='Region', columns="Product", aggfunc='median')

Product      A      B      C      D
Region
East     631.0    NaN    NaN    NaN
North      NaN    NaN  353.0    NaN
South      NaN    NaN    NaN  768.0
West       NaN  610.0    NaN    NaN

#### 4. Multiple Values Pivot

In [9]:
pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     640.4    NaN    NaN    NaN  45.8   NaN   NaN   NaN
North      NaN    NaN  398.2    NaN   NaN   NaN  53.6   NaN
South      NaN    NaN    NaN  665.8   NaN   NaN   NaN  49.2
West       NaN  543.4    NaN    NaN   NaN  72.0   NaN   NaN

#### 5. Crosstab

In [10]:
pd.crosstab(df['Region'], df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0